### ISSUE TITLE
Errors due to parallel docker-compose up/down in compose.bat

### ISSUE THREAD

**Issue by as-marcb** [RHEAGROUP/CDP4-Docker-Compose#11]
Using `START /B` in `compose.bat` leads to parallel execution of `docker-compose down` and  `docker-compose up` in
operations like `Up:`, `Reboot:`, ...

With certain timing conditions observed error cases include:
- untimely removal of network during/after container startup
  - container can not find network
  - trying to remove network while in use by containers
  - WebService unreachable
- untimely removal of `database` container while `webservice` is still initializing/running
- skipping `up` due to containers already running and only bringing them down instead

There may also be other effects/combinations.

If there is a reason to use `START /B` at all, it should be changed to `START /WAIT /B`.
Or dropped altogether.
Sequential calls to `docker-compose` are also used in the `compose.sh` script.

Synchronous invocation would in my opinion also improve command line output for `compose.bat` in case of single `docker-compose` operations.

**Comment by as-marcb** [comment]
Similar issue should pop up when using related script in [Webservices](/RHEAGROUP/CDP4-WebServices-Community-Edition/blob/development/compose.bat).
There is also a fix in [one location](/RHEAGROUP/CDP4-WebServices-Community-Edition/commit/b9acfacab137e15b089b6727aa57e76fd42190f3#diff-67c3713148e7550280ae53d3e89d423b5a1ef4183daa41b368ec7badea3df83aR39) (only) when executing `msbuild` as part of a task.

**Comment by lxatrhea** [comment]
@alexatrhea Could you provide some background info?
