### ISSUE TITLE
Update the scripts to install version 6.0.0 of the webservices and 

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-Docker-Compose#7]
I just followed the instructions from the README

  - pulled Git repos (master branch)
  - execute `compose.bat strt`

the script proceeded to download cdp4-services version 4.0.0 and database version 1.3.1

i was expecting version 6.0.0 of the cdp4-services and version 2.0.0. of the database:

![image](https://user-images.githubusercontent.com/22165725/93294275-5ba26a00-f7ea-11ea-8408-bc7b731ecee8.png)

![image](https://user-images.githubusercontent.com/22165725/93294295-6826c280-f7ea-11ea-916a-07851dbba67b.png)

**Comment by samatrhea** [comment]
i just noticed there is an approved PR https://github.com/RHEAGROUP/CDP4-Docker-Compose/pull/6 that fixes this; @alexatrhea please merge this to master. Also, please clean up any redundant branches

**Comment by alexatrhea** [comment]
Scripts are done already, wiki needs to be updated to reflect current postgres version.
